FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pandas==2.2.2 scikit-learn==1.3.2 joblib==1.4.2
COPY inference.py .
CMD ["python", "inference.py"]
