FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY RandomForest.py .
# no COPY ML_Final_Final.csv here
CMD ["python", "RandomForest.py"]
