FROM python:3.10
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install --no-cache-dir pandas==2.2.2 scikit-learn==1.3.2 joblib==1.4.2
COPY RandomForest.py .
COPY ML_Final_Final.csv .

CMD ["python", "RandomForest.py"]
