services:
  prep:
    build:
      context: .
      dockerfile: Dockerfile.prep
    command: python prep.py
    volumes:
      - ./ML_Final_Final.csv:/app/ML_Final_Final.csv

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    command: python RandomForest.py
    volumes:
      - ./ML_Final_Final.csv:/app/ML_Final_Final.csv

  inference:
    build:
      context: .
      dockerfile: Dockerfile.inference
    command: python inference.py
    volumes:
      - ./defect_prediction.pkl:/app/defect_prediction.pkl
