version: "3.9"

services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./ML_Final_Final.csv:/app/ML_Final_Final.csv
      - ./outputs:/app/outputs
    command: python RandomForest.py

inference:
  build:
    context: .
    dockerfile: Dockerfile.inference
  volumes:
    - ./outputs:/app/outputs        # trained model
    - ./new_data.csv:/app/new_data.csv   # new input data
  command: python inference.py
